/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProductColor = {
  _type: "productColor";
  name?: string;
  partNumber?: string;
  hex?: string;
};

export type ResourceLink = {
  _type: "resourceLink";
  title?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  externalUrl?: string;
};

export type SpecificationEntry = {
  _type: "specificationEntry";
  label?: string;
  value?: string;
};

export type BrandLogo = {
  _type: "brandLogo";
  name?: string;
  logo?: MediaAsset;
  href?: string;
};

export type IconFeature = {
  _type: "iconFeature";
  icon?: string;
  title?: string;
  description?: string;
};

export type MediaAsset = {
  _type: "mediaAsset";
  source?: "upload" | "external";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  externalUrl?: string;
  altText?: string;
};

export type LinkAction = {
  _type: "linkAction";
  label?: string;
  href?: string;
  icon?: string;
};

export type ProductProtocol = {
  _id: string;
  _type: "productProtocol";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  value?: string;
  description?: string;
  order?: number;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sku?: string;
  colors?: Array<{
    _key: string;
  } & ProductColor>;
  slug?: Slug;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productCategory";
  };
  voltage?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productVoltage";
  };
  frequency?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productFrequency";
  };
  protocols?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "productProtocol";
  }>;
  featureTag?: "featured" | "standard";
  shortDescription?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  specifications?: Array<{
    _key: string;
  } & SpecificationEntry>;
  images?: Array<{
    _key: string;
  } & MediaAsset>;
  downloads?: Array<{
    _key: string;
  } & ResourceLink>;
  applications?: Array<{
    title?: string;
    url?: string;
    _type: "application";
    _key: string;
  }>;
  wiringDiagrams?: Array<{
    _key: string;
  } & ResourceLink>;
};

export type ProductFrequency = {
  _id: string;
  _type: "productFrequency";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  value?: string;
  order?: number;
};

export type ProductVoltage = {
  _id: string;
  _type: "productVoltage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  value?: string;
  order?: number;
};

export type ProductCategory = {
  _id: string;
  _type: "productCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  order?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  excerpt?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  picture?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: AboutPageContent;
  companyInfo?: CompanyInfo;
};

export type CompanyInfo = {
  _type: "companyInfo";
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  email?: string;
  phone?: string;
  headquarters?: string;
  satelliteOffice?: string;
};

export type AboutPageContent = {
  _type: "aboutPageContent";
  heroDescription?: string;
  paragraphs?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HeroSection;
  controlSolutions?: ControlSolutionsSection;
  trustedBy?: TrustedBySection;
  about?: AboutSection;
};

export type AboutSection = {
  _type: "aboutSection";
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: LinkAction;
  background?: MediaAsset;
  features?: Array<{
    _key: string;
  } & IconFeature>;
};

export type TrustedBySection = {
  _type: "trustedBySection";
  heading?: string;
  logos?: Array<{
    _key: string;
  } & BrandLogo>;
};

export type ControlSolutionsSection = {
  _type: "controlSolutionsSection";
  title?: string;
  subtitle?: string;
  features?: Array<{
    _key: string;
  } & IconFeature>;
};

export type HeroSection = {
  _type: "heroSection";
  attentionLabel?: string;
  attentionIcon?: string;
  headline?: string;
  summary?: string;
  primaryAction?: LinkAction;
  secondaryAction?: LinkAction;
  backgroundImage?: MediaAsset;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = ProductColor | ResourceLink | SpecificationEntry | BrandLogo | IconFeature | MediaAsset | LinkAction | ProductProtocol | Product | ProductFrequency | ProductVoltage | ProductCategory | Post | Author | AboutPage | CompanyInfo | AboutPageContent | HomePage | AboutSection | TrustedBySection | ControlSolutionsSection | HeroSection | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(frontend)/posts/[slug]/page.tsx
// Variable: postSlugs
// Query: *[_type == "post" && defined(slug.current)]{"slug": slug.current}
export type PostSlugsResult = Array<{
  slug: string | null;
}>;

// Source: ./app/(frontend)/products/[slug]/page.tsx
// Variable: productSlugs
// Query: *[_type == "product" && defined(slug.current)]{"slug": slug.current}
export type ProductSlugsResult = Array<{
  slug: string | null;
}>;

// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = null;
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{    hero{      attentionLabel,      attentionIcon,      headline,      summary,      primaryAction{        label,        href,        icon      },      secondaryAction{        label,        href,        icon      },      backgroundImage{        source,        altText,        externalUrl,        image{          asset,          crop,          hotspot        }      }    },    controlSolutions{      title,      subtitle,      features[]{        icon,        title,        description      }    },    trustedBy{      heading,      logos[]{        name,        href,        logo{          source,          altText,          externalUrl,          image{            asset,            crop,            hotspot          }        }      }    },    about{      title,      body[]{        ...,        children[]{          ...        }      },      cta{        label,        href,        icon      },      background{        source,        altText,        externalUrl,        image{          asset,          crop,          hotspot        }      },      features[]{        icon,        title,        description      }    }  }
export type HomePageQueryResult = {
  hero: {
    attentionLabel: string | null;
    attentionIcon: string | null;
    headline: string | null;
    summary: string | null;
    primaryAction: {
      label: string | null;
      href: string | null;
      icon: string | null;
    } | null;
    secondaryAction: {
      label: string | null;
      href: string | null;
      icon: string | null;
    } | null;
    backgroundImage: {
      source: "external" | "upload" | null;
      altText: string | null;
      externalUrl: string | null;
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      } | null;
    } | null;
  } | null;
  controlSolutions: {
    title: string | null;
    subtitle: string | null;
    features: Array<{
      icon: string | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  trustedBy: {
    heading: string | null;
    logos: Array<{
      name: string | null;
      href: string | null;
      logo: {
        source: "external" | "upload" | null;
        altText: string | null;
        externalUrl: string | null;
        image: {
          asset: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
        } | null;
      } | null;
    }> | null;
  } | null;
  about: {
    title: string | null;
    body: Array<{
      children: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }> | null;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: {
      label: string | null;
      href: string | null;
      icon: string | null;
    } | null;
    background: {
      source: "external" | "upload" | null;
      altText: string | null;
      externalUrl: string | null;
      image: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      } | null;
    } | null;
    features: Array<{
      icon: string | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
} | null;
// Variable: categoryQuery
// Query: *[_type == "productCategory"] {    _id,    "slug": slug.current,    title,    description  } | order(_createdAt desc)
export type CategoryQueryResult = Array<{
  _id: string;
  slug: string | null;
  title: string | null;
  description: string | null;
}>;
// Variable: productFrequencyQuery
// Query: *[_type == "productFrequency"] {    _id,    "value": value,    label  } | order(_createdAt desc)
export type ProductFrequencyQueryResult = Array<{
  _id: string;
  value: string | null;
  label: string | null;
}>;
// Variable: productProtocolQuery
// Query: *[_type == "productProtocol"] {    _id,    "value": value,    label  } | order(_createdAt desc)
export type ProductProtocolQueryResult = Array<{
  _id: string;
  value: string | null;
  label: string | null;
}>;
// Variable: productVoltageQuery
// Query: *[_type == "productVoltage"] {    _id,    "value": value,    label  } | order(_createdAt desc)
export type ProductVoltageQueryResult = Array<{
  _id: string;
  value: string | null;
  label: string | null;
}>;
// Variable: heroQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) [0] {    content,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  }
export type HeroQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
} | null;
// Variable: moreStoriesQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  }
export type MoreStoriesQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  }
export type PostQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
} | null;
// Variable: featuredProductsQuery
// Query: *[_type == "product" && featureTag == "featured"]{      _id,    title,    "slug": slug.current,    shortDescription,    "image": images[0]{         source,        altText,        externalUrl,        image{          asset,          crop,          hotspot        }    },    "category": category->slug.current,    "sku": sku,    colors[]{      name,      partNumber,      hex    },  } | order(_createdAt desc)[0...8]
export type FeaturedProductsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  image: {
    source: "external" | "upload" | null;
    altText: string | null;
    externalUrl: string | null;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  category: string | null;
  sku: string | null;
  colors: Array<{
    name: string | null;
    partNumber: string | null;
    hex: string | null;
  }> | null;
}>;
// Variable: allProductsQuery
// Query: *[_type == "product"]{      _id,    title,    "slug": slug.current,    shortDescription,    "image": images[0]{         source,        altText,        externalUrl,        image{          asset,          crop,          hotspot        }    },    "category": category->slug.current,    "sku": sku,    colors[]{      name,      partNumber,      hex    },  } | order(_createdAt desc)
export type AllProductsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  image: {
    source: "external" | "upload" | null;
    altText: string | null;
    externalUrl: string | null;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  category: string | null;
  sku: string | null;
  colors: Array<{
    name: string | null;
    partNumber: string | null;
    hex: string | null;
  }> | null;
}>;
// Variable: FILTERED_PRODUCTS_COUNT_QUERY
// Query: count(    *[      _type == "product" &&      (        !defined($search) ||        $search == "" ||        coalesce(title, "") match $searchWildcard ||        coalesce(sku.current, "") match $searchWildcard      ) &&      (        !defined($category) ||        $category == "" ||        category->slug.current == $category      ) &&      (        !defined($voltage) ||        $voltage == "" ||        voltage->value == $voltage      ) &&      (        !defined($frequency) ||        $frequency == "" ||        frequency->value == $frequency      ) &&      (        !defined($protocols) ||        count($protocols) == 0 ||        count((protocols[]->value)[@ in $protocols]) > 0      )    ]  )
export type FILTERED_PRODUCTS_COUNT_QUERYResult = number;
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{      _id,      title,      "slug": slug.current,      sku,      shortDescription,      body[]{        ...,        children[]{          ...        }      },      "category": category->{        _id,        title,        "slug": slug.current      },      "voltage": voltage->{ _id, label, value },      "frequency": frequency->{ _id, label, value },      "protocols": protocols[]->{ _id, label, value },      featureTag,      colors[]{        name,        partNumber,        hex      },      images[]{        source,        altText,        externalUrl,        image{          asset,          crop,          hotspot        }      },      specifications[defined(label) && defined(value)]{        _type,        label,        value      },      downloads[defined(title) && defined(file.asset)]{        _type,        title,        file{          asset->{            _id,            url,            originalFilename,            size          }        },        externalUrl      },      applications[defined(url)]{        _type,        title,        url      },      wiringDiagrams[defined(title) && defined(file.asset)]{        _type,        title,        file{          asset->{            _id,            url,            originalFilename,            size          }        },        externalUrl      }    }
export type PRODUCT_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  sku: string | null;
  shortDescription: string | null;
  body: Array<{
    children: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }> | null;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  voltage: {
    _id: string;
    label: string | null;
    value: string | null;
  } | null;
  frequency: {
    _id: string;
    label: string | null;
    value: string | null;
  } | null;
  protocols: Array<{
    _id: string;
    label: string | null;
    value: string | null;
  }> | null;
  featureTag: "featured" | "standard" | null;
  colors: Array<{
    name: string | null;
    partNumber: string | null;
    hex: string | null;
  }> | null;
  images: Array<{
    source: "external" | "upload" | null;
    altText: string | null;
    externalUrl: string | null;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  }> | null;
  specifications: Array<{
    _type: "specificationEntry";
    label: string | null;
    value: string | null;
  }> | null;
  downloads: Array<{
    _type: "resourceLink";
    title: string | null;
    file: {
      asset: {
        _id: string;
        url: string | null;
        originalFilename: string | null;
        size: number | null;
      } | null;
    } | null;
    externalUrl: string | null;
  }> | null;
  applications: Array<{
    _type: "application";
    title: string | null;
    url: string | null;
  }> | null;
  wiringDiagrams: Array<{
    _type: "resourceLink";
    title: string | null;
    file: {
      asset: {
        _id: string;
        url: string | null;
        originalFilename: string | null;
        size: number | null;
      } | null;
    } | null;
    externalUrl: string | null;
  }> | null;
} | null;
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{    content{      heroDescription,      paragraphs[]{        ...,        children[]{          ...        }      }    },    companyInfo{      overview[]{        ...,        children[]{          ...        }      },      email,      phone,      headquarters,      satelliteOffice    }  }
export type AboutPageQueryResult = {
  content: {
    heroDescription: string | null;
    paragraphs: Array<{
      children: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }> | null;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  companyInfo: {
    overview: Array<{
      children: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }> | null;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    email: string | null;
    phone: string | null;
    headquarters: string | null;
    satelliteOffice: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"post\" && defined(slug.current)]{\"slug\": slug.current}": PostSlugsResult;
    "*[_type == \"product\" && defined(slug.current)]{\"slug\": slug.current}": ProductSlugsResult;
    "*[_type == \"settings\"][0]": SettingsQueryResult;
    "\n  *[_type == \"homePage\"][0]{\n    hero{\n      attentionLabel,\n      attentionIcon,\n      headline,\n      summary,\n      primaryAction{\n        label,\n        href,\n        icon\n      },\n      secondaryAction{\n        label,\n        href,\n        icon\n      },\n      backgroundImage{\n        source,\n        altText,\n        externalUrl,\n        image{\n          asset,\n          crop,\n          hotspot\n        }\n      }\n    },\n    controlSolutions{\n      title,\n      subtitle,\n      features[]{\n        icon,\n        title,\n        description\n      }\n    },\n    trustedBy{\n      heading,\n      logos[]{\n        name,\n        href,\n        logo{\n          source,\n          altText,\n          externalUrl,\n          image{\n            asset,\n            crop,\n            hotspot\n          }\n        }\n      }\n    },\n    about{\n      title,\n      body[]{\n        ...,\n        children[]{\n          ...\n        }\n      },\n      cta{\n        label,\n        href,\n        icon\n      },\n      background{\n        source,\n        altText,\n        externalUrl,\n        image{\n          asset,\n          crop,\n          hotspot\n        }\n      },\n      features[]{\n        icon,\n        title,\n        description\n      }\n    }\n  }\n": HomePageQueryResult;
    "\n  *[_type == \"productCategory\"] {\n    _id,\n    \"slug\": slug.current,\n    title,\n    description\n  } | order(_createdAt desc)  \n": CategoryQueryResult;
    "\n  *[_type == \"productFrequency\"] {\n    _id,\n    \"value\": value,\n    label\n  } | order(_createdAt desc)  \n": ProductFrequencyQueryResult;
    "\n  *[_type == \"productProtocol\"] {\n    _id,\n    \"value\": value,\n    label\n  } | order(_createdAt desc)\n": ProductProtocolQueryResult;
    "\n  *[_type == \"productVoltage\"] {\n    _id,\n    \"value\": value,\n    label\n  } | order(_createdAt desc)\n": ProductVoltageQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current)] | order(date desc, _updatedAt desc) [0] {\n    content,\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n\n  }\n": HeroQueryResult;
    "\n  *[_type == \"post\" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n\n  }\n": MoreStoriesQueryResult;
    "\n  *[_type == \"post\" && slug.current == $slug] [0] {\n    content,\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n\n  }\n": PostQueryResult;
    "\n  *[_type == \"product\" && featureTag == \"featured\"]{\n   \n   _id,\n    title,\n    \"slug\": slug.current,\n    shortDescription,\n    \"image\": images[0]{ \n        source,\n        altText,\n        externalUrl,\n        image{\n          asset,\n          crop,\n          hotspot\n        }\n    },\n    \"category\": category->slug.current,\n    \"sku\": sku,\n    colors[]{\n      name,\n      partNumber,\n      hex\n    },\n\n  } | order(_createdAt desc)[0...8]\n": FeaturedProductsQueryResult;
    "\n  *[_type == \"product\"]{\n   \n   _id,\n    title,\n    \"slug\": slug.current,\n    shortDescription,\n    \"image\": images[0]{ \n        source,\n        altText,\n        externalUrl,\n        image{\n          asset,\n          crop,\n          hotspot\n        }\n    },\n    \"category\": category->slug.current,\n    \"sku\": sku,\n    colors[]{\n      name,\n      partNumber,\n      hex\n    },\n\n  } | order(_createdAt desc)\n": AllProductsQueryResult;
    "\n  count(\n    *[\n      _type == \"product\" &&\n      (\n        !defined($search) ||\n        $search == \"\" ||\n        coalesce(title, \"\") match $searchWildcard ||\n        coalesce(sku.current, \"\") match $searchWildcard\n      ) &&\n      (\n        !defined($category) ||\n        $category == \"\" ||\n        category->slug.current == $category\n      ) &&\n      (\n        !defined($voltage) ||\n        $voltage == \"\" ||\n        voltage->value == $voltage\n      ) &&\n      (\n        !defined($frequency) ||\n        $frequency == \"\" ||\n        frequency->value == $frequency\n      ) &&\n      (\n        !defined($protocols) ||\n        count($protocols) == 0 ||\n        count((protocols[]->value)[@ in $protocols]) > 0\n      )\n    ]\n  )\n  ": FILTERED_PRODUCTS_COUNT_QUERYResult;
    "\n    *[_type == \"product\" && slug.current == $slug][0]{\n      _id,\n      title,\n      \"slug\": slug.current,\n      sku,\n      shortDescription,\n      body[]{\n        ...,\n        children[]{\n          ...\n        }\n      },\n      \"category\": category->{\n        _id,\n        title,\n        \"slug\": slug.current\n      },\n      \"voltage\": voltage->{ _id, label, value },\n      \"frequency\": frequency->{ _id, label, value },\n      \"protocols\": protocols[]->{ _id, label, value },\n      featureTag,\n      colors[]{\n        name,\n        partNumber,\n        hex\n      },\n      images[]{\n        source,\n        altText,\n        externalUrl,\n        image{\n          asset,\n          crop,\n          hotspot\n        }\n      },\n      specifications[defined(label) && defined(value)]{\n        _type,\n        label,\n        value\n      },\n      downloads[defined(title) && defined(file.asset)]{\n        _type,\n        title,\n        file{\n          asset->{\n            _id,\n            url,\n            originalFilename,\n            size\n          }\n        },\n        externalUrl\n      },\n      applications[defined(url)]{\n        _type,\n        title,\n        url\n      },\n      wiringDiagrams[defined(title) && defined(file.asset)]{\n        _type,\n        title,\n        file{\n          asset->{\n            _id,\n            url,\n            originalFilename,\n            size\n          }\n        },\n        externalUrl\n      }\n    }\n    ": PRODUCT_QUERYResult;
    "\n  *[_type == \"aboutPage\"][0]{\n    content{\n      heroDescription,\n      paragraphs[]{\n        ...,\n        children[]{\n          ...\n        }\n      }\n    },\n    companyInfo{\n      overview[]{\n        ...,\n        children[]{\n          ...\n        }\n      },\n      email,\n      phone,\n      headquarters,\n      satelliteOffice\n    }\n  }\n": AboutPageQueryResult;
  }
}
